### ISSUE TITLE
上传文件后生成的fileInfo.url没有拼接bucket-name

### ISSUE THREAD

**Issue by Gerrit1999** [1171736840/spring-file-storage#101]
配置文件:
```yaml
spring:
  file-storage:
    default-platform: ceph-1
    amazon-s3:
      - platform: ceph-1
        enable-storage: true 
        access-key: xxx
        secret-key: xxx
        endpoint: 127.0.0.1:7480
        bucket-name: my-new-bucket
        domain: http://127.0.0.1:7480/
        base-path: s3/
```
测试代码:
```java
@Test
void test() {
    FileInfo fileInfo = fileStorageService.of(new File("E:\\test.jpg")).setFileAcl(Constant.ACL.PUBLIC_READ).upload();
    System.out.println("fileInfo = " + fileInfo);
}
```
输出:
```
fileInfo = FileInfo(id=null, url=http://127.0.0.1:7480/s3/64d19b5f10a5c2efe3b59b17.jpg, size=723542, ...)
```
正确的url应该是:
```
http://127.0.0.1:7480/my-new-bucket/s3/64d19b5f10a5c2efe3b59b17.jpg
```
