### ISSUE TITLE
使用S3通过MultipartFile上传文件出现com.amazonaws.ResetException异常

### ISSUE THREAD

**Issue by Gerrit1999** [1171736840/spring-file-storage#110]
与[stackoverflow](https://stackoverflow.com/questions/53446818/amazon-s3-uploading-via-java-api-inputstream-sources)中的问题一致

**Comment by 1171736840** [comment]
请提供你的代码

**Comment by Gerrit1999** [comment]
service:
```java
public FileDetail upload(@NonNull MultipartFile file, boolean generateThumbnail) {
    String contentType = file.getContentType();
    FileInfo info = storageService.of(file)
            // 缩略图配置
            .thumbnail(generateThumbnail &&
                    contentType != null &&
                    contentType.matches("^image/(jpeg|png|gif)$"))
            // 相对路径设置为日期
            .setPath(FastDateFormat.getInstance("yyyy/MM/dd/").format(new Date()))
            .upload();
    return BeanUtil.copyProperties(info, FileDetail.class);
}
```
配置文件:
```yaml
spring:
  # 文件存储配置
  file-storage:
    default-platform: amazon-s3-1 # 默认使用的存储平台
    thumbnail-suffix: .min.png # 缩略图后缀
    # 对应平台的配置
    amazon-s3:
      - platform: amazon-s3-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: 
        secret-key: 
        end-point: http://localhost:7480
        bucket-name: demo
        domain: ${spring.file-storage.amazon-s3[0].endpoint}/${spring.file-storage.amazon-s3[0].bucket-name}/ # 访问域名, 注意"/"结尾
```
